#:schema node_modules/wrangler/config-schema.json

name = "exa-search-engine"
main = ".open-next/worker.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat_v2"]

# 静态资源
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
# 环境变量通过 wrangler secret put EXA_API_KEY 设置
